// =====================================
// RIGO AI
// PLANNER CONFIG
// =====================================

export const PLANNER_ENGINE_CONFIG =
Object.freeze({

  ENABLE_DYNAMIC_PLANNING:true,

  ENABLE_GOAL_DECOMPOSITION:true,

  ENABLE_REPLANNING:true,

  ENABLE_AGENT_ASSIGNMENT:true,

  ENABLE_TOOL_SELECTION:true,

  ENABLE_ADAPTIVE_STRATEGIES:true,

  ENABLE_PLAN_MEMORY:true,

  ENABLE_DIAGNOSTICS:true,

  ENABLE_PLAN_ABORT:true,

  ENABLE_PLAN_QUEUE:true,

  ENABLE_AUTO_QUEUE_DRAIN:true,

  ENABLE_EXECUTION_HISTORY:true,

  ENABLE_RUNTIME_SYNC:true,

  MAX_PLANS:1000,

  MAX_PLAN_STEPS:200,

  MAX_RETRIES:3,

  MAX_PARALLEL_PLANS:50,

  MAX_QUEUE_SIZE:500,

  MAX_CONTEXT_SIZE:100000,

  PLAN_TIMEOUT:300000,

  RETRY_DELAY:500,

  MAX_EXECUTION_HISTORY:500

});
