import assert from "node:assert/strict";
import {readFile} from "node:fs/promises";
const page=await readFile(new URL("../js/admin/studio/pages/debug-page.js",import.meta.url),"utf8");
assert.match(page,/id:"debug",title:"Debug Center"/);
assert.match(page,/Run Diagnostics/);
assert.match(page,/Captured Issues/);
assert.match(page,/Promise rejections/);
assert.match(page,/Diagnostics completed successfully/);
assert.match(page,/Debug report generated successfully/);
assert.match(page,/Captured errors refreshed successfully/);
assert.match(page,/Latest Report/);
const workspace=await readFile(new URL("../js/admin/studio/workspace/index.js",import.meta.url),"utf8");
assert.match(workspace,/WorkspaceManager\.register\(DebugPage\)/);
console.log("Admin Debug Center page tests passed.");
