import DebugAgentState from "./debug-agent-state.js";
let debugModule=null;
async function getDebug(){if(debugModule)return debugModule;const imported=await import("../../../../debug/index.js");debugModule=imported.default;return debugModule;}
function initialize(){if(DebugAgentState.state.initialized)return true;DebugAgentState.set({initialized:true});DebugAgentState.log("system","DEBUG AGENT INITIALIZED");return true;}
async function boot(){initialize();DebugAgentState.set({booted:true});return true;}
function count(value){if(Array.isArray(value))return value.length;if(typeof value==="number")return value;if(value&&typeof value==="object")return Object.keys(value).length;return 0;}
export function analyzeDebugSnapshot(snapshot={}){const diagnostics=snapshot.diagnostics||{};const runtime=snapshot.runtime||{};const syntax=snapshot.syntax||{};const circular=snapshot.circular||{};const dependency=snapshot.dependency||{};const errors=count(diagnostics.errors)+count(runtime.runtimeErrors)+count(runtime.promiseRejections)+count(syntax.errors);const warnings=count(diagnostics.warnings)+count(dependency.missing)+count(dependency.invalid);const critical=count(diagnostics.critical)+count(runtime.crashes);const circularDependencies=count(circular.circularFound||circular.cycles);const healthScore=Number.isFinite(diagnostics.healthScore)?diagnostics.healthScore:Math.max(0,100-errors*10-warnings*3-critical*20-circularDependencies*5);return{healthy:errors===0&&critical===0,healthScore,errors,warnings,critical,circularDependencies,runtime:{errors:count(runtime.runtimeErrors),rejections:count(runtime.promiseRejections),crashes:count(runtime.crashes)},system:snapshot.system||null,timestamp:Date.now()};}
async function capture(){initialize();try{const Debug=await getDebug();const raw=Debug.snapshot();const analysis=analyzeDebugSnapshot(raw);DebugAgentState.state.diagnostics.runs++;DebugAgentState.state.diagnostics.errors=analysis.errors;DebugAgentState.state.diagnostics.warnings=analysis.warnings;DebugAgentState.state.diagnostics.critical=analysis.critical;DebugAgentState.set({lastSnapshot:raw,lastReport:analysis,lastError:null});return{ok:true,mode:"debug-diagnostics",analysis,snapshot:raw};}catch(error){DebugAgentState.set({lastError:error});return{ok:false,error:error?.message||String(error)};}}
async function report(){initialize();try{const Debug=await getDebug();const report=Debug.report();const diagnostic=await capture();return{ok:true,mode:"debug-report",report,diagnostic:diagnostic.analysis||null};}catch(error){DebugAgentState.set({lastError:error});return{ok:false,error:error?.message||String(error)};}}
async function errors(){const result=await capture();if(!result.ok)return result;const d=result.snapshot.diagnostics||{},r=result.snapshot.runtime||{};return{ok:true,mode:"debug-errors",errors:d.errors||[],critical:d.critical||[],runtimeErrors:r.runtimeErrors||[],promiseRejections:r.promiseRejections||[],crashes:r.crashes||[]};}
async function shutdown(){DebugAgentState.set({booted:false});return true;}async function reset(){debugModule=null;return DebugAgentState.reset();}const snapshot=()=>DebugAgentState.snapshot();const DebugAgent=Object.freeze({id:"debug-agent",priority:60,initialize,boot,capture,report,errors,shutdown,reset,snapshot});export{initialize,boot,capture,report,errors,shutdown,reset,snapshot,DebugAgent};export default DebugAgent;
