import crypto from "node:crypto";
function neon(connectionString){const parsed=new URL(connectionString);const labels=parsed.hostname.split(".");const apiHost=labels[0]?.startsWith("ep-")?`api.${labels.slice(1).join(".")}`:parsed.hostname;const endpoint=`https://${apiHost}/sql`;return async function sql(strings,...values){let query=strings[0]||"";const params=[];for(let i=0;i<values.length;i++){query+=`${i+1}${strings[i+1]||""}`;params.push(values[i])}const response=await fetch(endpoint,{method:"POST",headers:{"Content-Type":"application/json","Neon-Connection-String":connectionString},body:JSON.stringify({query,params})});const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload?.message||payload?.error||`DATABASE_QUERY_FAILED_${response.status}`);return Array.isArray(payload?.rows)?payload.rows:[]}}

const COOKIE_NAME="rigo_session";
const SESSION_AGE=60*60*24*30;
const SESSION_AGE_PERSISTENT=60*60*24*400;
const OTP_TTL_MS=10*60*1000;
const OTP_RESEND_MS=60*1000;

function bodyOf(req){if(req.body&&typeof req.body==="object")return req.body;if(typeof req.body==="string"){try{return JSON.parse(req.body)}catch{return {}}}return {}}
function emailOf(v){return String(v||"").trim().toLowerCase()}
function databaseUrl(){return process.env.DATABASE_URL||process.env.DATABASE_POSTGRES_URL||process.env.POSTGRES_URL||process.env.DATABASE_NEON_URL||""}
function secret(){return process.env.RIGO_SESSION_SECRET||process.env.RIGO_ADMIN_SESSION_SECRET||process.env.OPENROUTER_API_KEY||""}
function sql(){const url=databaseUrl();if(!url)throw new Error("DATABASE_URL_NOT_CONFIGURED");return neon(url)}
function b64(v){return Buffer.from(v,"utf8").toString("base64url")}
function unb64(v){return Buffer.from(v,"base64url").toString("utf8")}
function sign(v){return crypto.createHmac("sha256",secret()).update(v).digest("base64url")}
function equal(a,b){const x=Buffer.from(String(a));const y=Buffer.from(String(b));return x.length===y.length&&crypto.timingSafeEqual(x,y)}
function hashPassword(password,salt=crypto.randomBytes(16).toString("hex")){const hash=crypto.scryptSync(String(password),salt,64).toString("hex");return `${salt}:${hash}`}
function verifyPassword(password,stored){try{const [salt,expected]=String(stored).split(":");const actual=crypto.scryptSync(String(password),salt,64).toString("hex");return equal(actual,expected)}catch{return false}}
function cookies(req){const out={};for(const part of String(req.headers?.cookie||"").split(";")){const i=part.indexOf("=");if(i>0)out[part.slice(0,i).trim()]=decodeURIComponent(part.slice(i+1).trim())}return out}
function tokenFor(user,persistent){if(!secret())throw new Error("RIGO_SESSION_SECRET_NOT_CONFIGURED");const payload=b64(JSON.stringify({id:user.id,email:user.email,role:user.role||"user",exp:Date.now()+1000*(persistent?SESSION_AGE_PERSISTENT:SESSION_AGE)}));return `${payload}.${sign(payload)}`}
function readToken(req){try{const token=cookies(req)[COOKIE_NAME];if(!token)return null;const [payload,sig]=token.split(".");if(!payload||!sig||!equal(sig,sign(payload)))return null;const data=JSON.parse(unb64(payload));return data.exp>Date.now()?data:null}catch{return null}}
function setSession(res,user,persistent){const max=persistent?SESSION_AGE_PERSISTENT:SESSION_AGE;res.setHeader("Set-Cookie",`${COOKIE_NAME}=${encodeURIComponent(tokenFor(user,persistent))}; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=${max}`)}
function clearSession(res){res.setHeader("Set-Cookie",`${COOKIE_NAME}=; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=0`)}
function publicUser(u){return {id:u.id,email:u.email,name:u.name||"",role:u.role||"user"}}
function otpCode(){return String(crypto.randomInt(100000,1000000))}
function otpHash(code){return crypto.createHash("sha256").update(`${secret()}:${String(code)}`).digest("hex")}
function validPassword(password){return String(password||"").length>=8}
function mailConfig(){return {key:process.env.RESEND_API_KEY||"",from:process.env.RIGO_FROM_EMAIL||""}}
async function sendOtpEmail({to,code,purpose}){const cfg=mailConfig();if(!cfg.key||!cfg.from)throw new Error("EMAIL_PROVIDER_NOT_CONFIGURED");const subject=purpose==="reset"?"RIGO AI password reset code":"RIGO AI verification code";const response=await fetch("https://api.resend.com/emails",{method:"POST",headers:{"Authorization":`Bearer ${cfg.key}`,"Content-Type":"application/json"},body:JSON.stringify({from:cfg.from,to:[to],subject,html:`<div style="font-family:Arial,sans-serif"><h2>RIGO AI</h2><p>Your verification code is:</p><p style="font-size:32px;font-weight:700;letter-spacing:8px">${code}</p><p>This code expires in 10 minutes.</p></div>`})});let payload={};try{payload=await response.json()}catch{}if(!response.ok)throw new Error(payload?.message||payload?.error||"EMAIL_DELIVERY_FAILED");return payload?.id||null}
async function issueOtp(db,userId,email,purpose){const now=Date.now();const recent=await db`SELECT otp_sent_at FROM rigo_users WHERE id=${userId} LIMIT 1`;const sentAt=recent[0]?.otp_sent_at?new Date(recent[0].otp_sent_at).getTime():0;const elapsed=now-sentAt;if(sentAt&&elapsed<OTP_RESEND_MS){const error=new Error("OTP_COOLDOWN");error.retryAfter=Math.ceil((OTP_RESEND_MS-elapsed)/1000);throw error}const code=otpCode();const emailId=await sendOtpEmail({to:email,code,purpose});await db`UPDATE rigo_users SET otp_hash=${otpHash(code)},otp_expires_at=${new Date(now+OTP_TTL_MS)},otp_purpose=${purpose},otp_sent_at=NOW(),updated_at=NOW() WHERE id=${userId}`;return {sent:true,emailId}
async function ensureSchema(db){
 await db`CREATE TABLE IF NOT EXISTS rigo_users (id UUID PRIMARY KEY,email TEXT NOT NULL UNIQUE,name TEXT NOT NULL DEFAULT '',password_hash TEXT NOT NULL,role TEXT NOT NULL DEFAULT 'user',email_verified_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),otp_hash TEXT,otp_expires_at TIMESTAMPTZ,otp_purpose TEXT,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`;
 await db`ALTER TABLE rigo_users ADD COLUMN IF NOT EXISTS name TEXT NOT NULL DEFAULT ''`;
 await db`ALTER TABLE rigo_users ADD COLUMN IF NOT EXISTS email_verified_at TIMESTAMPTZ`;
 await db`ALTER TABLE rigo_users ADD COLUMN IF NOT EXISTS otp_hash TEXT`;
 await db`ALTER TABLE rigo_users ADD COLUMN IF NOT EXISTS otp_expires_at TIMESTAMPTZ`;
 await db`ALTER TABLE rigo_users ADD COLUMN IF NOT EXISTS otp_purpose TEXT`;
 await db`ALTER TABLE rigo_users ADD COLUMN IF NOT EXISTS otp_sent_at TIMESTAMPTZ`;
 await db`UPDATE rigo_users SET email_verified_at=COALESCE(email_verified_at,created_at) WHERE email_verified_at IS NULL`;
 await db`CREATE TABLE IF NOT EXISTS rigo_conversations (id UUID PRIMARY KEY,user_id UUID NOT NULL REFERENCES rigo_users(id) ON DELETE CASCADE,title TEXT NOT NULL DEFAULT '',created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`;
 await db`CREATE INDEX IF NOT EXISTS rigo_conversations_user_idx ON rigo_conversations(user_id,updated_at DESC)`;
 await db`CREATE TABLE IF NOT EXISTS rigo_messages (id UUID PRIMARY KEY,conversation_id UUID NOT NULL REFERENCES rigo_conversations(id) ON DELETE CASCADE,user_id UUID NOT NULL REFERENCES rigo_users(id) ON DELETE CASCADE,role TEXT NOT NULL,content TEXT NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`;
 await db`CREATE INDEX IF NOT EXISTS rigo_messages_user_idx ON rigo_messages(user_id,created_at)`;
 await db`CREATE TABLE IF NOT EXISTS rigo_memory (id UUID PRIMARY KEY,user_id UUID NOT NULL REFERENCES rigo_users(id) ON DELETE CASCADE,memory_key TEXT NOT NULL,memory_value JSONB NOT NULL DEFAULT '{}'::jsonb,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),UNIQUE(user_id,memory_key))`;
 await db`CREATE INDEX IF NOT EXISTS rigo_memory_user_idx ON rigo_memory(user_id)`;
 await db`CREATE TABLE IF NOT EXISTS rigo_storage (id UUID PRIMARY KEY,user_id UUID NOT NULL REFERENCES rigo_users(id) ON DELETE CASCADE,storage_key TEXT NOT NULL,storage_value JSONB NOT NULL DEFAULT '{}'::jsonb,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),UNIQUE(user_id,storage_key))`;
 await db`CREATE INDEX IF NOT EXISTS rigo_storage_user_idx ON rigo_storage(user_id)`;
}
export default async function handler(req,res){
 res.setHeader("Cache-Control","no-store");const body=bodyOf(req);const action=String(req.query?.action||body.action||"");
 try{const db=sql();await ensureSchema(db);
  if(action==="register"){if(req.method!=="POST")return res.status(405).json({ok:false,error:"METHOD_NOT_ALLOWED"});const email=emailOf(body.email),password=String(body.password||""),name=String(body.name||"").trim();if(!email||!email.includes("@"))return res.status(400).json({ok:false,error:"INVALID_EMAIL"});if(!validPassword(password))return res.status(400).json({ok:false,error:"PASSWORD_TOO_SHORT"});const exists=await db`SELECT id FROM rigo_users WHERE email=${email} LIMIT 1`;if(exists.length)return res.status(409).json({ok:false,error:"ACCOUNT_ALREADY_EXISTS"});if(!mailConfig().key||!mailConfig().from)return res.status(503).json({ok:false,error:"EMAIL_PROVIDER_NOT_CONFIGURED"});const id=crypto.randomUUID(),passwordHash=hashPassword(password);const rows=await db`INSERT INTO rigo_users(id,email,name,password_hash,email_verified_at) VALUES(${id},${email},${name},${passwordHash},NULL) RETURNING id,email,name,role`;try{await issueOtp(db,id,email,"verify")}catch(error){await db`DELETE FROM rigo_users WHERE id=${id}`;throw error}return res.status(201).json({ok:true,verificationRequired:true,user:publicUser(rows[0])})}
  if(action==="verify"){if(req.method!=="POST")return res.status(405).json({ok:false,error:"METHOD_NOT_ALLOWED"});const email=emailOf(body.email),code=String(body.code||"").trim();if(!email||!/^\d{6}$/.test(code))return res.status(400).json({ok:false,error:"INVALID_CODE"});const rows=await db`SELECT id,email,name,role,otp_hash,otp_expires_at,otp_purpose FROM rigo_users WHERE email=${email} LIMIT 1`;const user=rows[0];if(!user||user.otp_purpose!=="verify"||!user.otp_expires_at||new Date(user.otp_expires_at).getTime()<Date.now()||!equal(otpHash(code),user.otp_hash))return res.status(400).json({ok:false,error:"INVALID_OR_EXPIRED_CODE"});await db`UPDATE rigo_users SET email_verified_at=NOW(),otp_hash=NULL,otp_expires_at=NULL,otp_purpose=NULL,otp_sent_at=NULL,updated_at=NOW() WHERE id=${user.id}`;setSession(res,user,Boolean(body.staySignedIn));return res.status(200).json({ok:true,user:publicUser(user),role:user.role})}
  if(action==="resend"){if(req.method!=="POST")return res.status(405).json({ok:false,error:"METHOD_NOT_ALLOWED"});const email=emailOf(body.email),purpose=body.purpose==="reset"?"reset":"verify";const rows=await db`SELECT id,email,name,role,email_verified_at FROM rigo_users WHERE email=${email} LIMIT 1`;const user=rows[0];if(!user)return res.status(200).json({ok:true});if(purpose==="verify"&&user.email_verified_at)return res.status(400).json({ok:false,error:"ALREADY_VERIFIED"});try{const result=await issueOtp(db,user.id,user.email,purpose);return res.status(200).json({ok:true,...result})}catch(error){if(error?.message==="OTP_COOLDOWN")return res.status(429).json({ok:false,error:"OTP_COOLDOWN",retryAfter:error.retryAfter||60});throw error}}
  if(action==="request-reset"){if(req.method!=="POST")return res.status(405).json({ok:false,error:"METHOD_NOT_ALLOWED"});if(!mailConfig().key||!mailConfig().from)return res.status(503).json({ok:false,error:"EMAIL_PROVIDER_NOT_CONFIGURED"});const email=emailOf(body.email);const rows=await db`SELECT id,email FROM rigo_users WHERE email=${email} LIMIT 1`;if(rows.length){try{const result=await issueOtp(db,rows[0].id,rows[0].email,"reset");return res.status(200).json({ok:true,...result})}catch(error){if(error?.message==="OTP_COOLDOWN")return res.status(429).json({ok:false,error:"OTP_COOLDOWN",retryAfter:error.retryAfter||60});throw error}}return res.status(200).json({ok:true})}
  if(action==="reset-password"){if(req.method!=="POST")return res.status(405).json({ok:false,error:"METHOD_NOT_ALLOWED"});const email=emailOf(body.email),code=String(body.code||"").trim(),password=String(body.password||"");if(!email||!/^\d{6}$/.test(code)||!validPassword(password))return res.status(400).json({ok:false,error:"INVALID_RESET_REQUEST"});const rows=await db`SELECT id,email,name,role,otp_hash,otp_expires_at,otp_purpose FROM rigo_users WHERE email=${email} LIMIT 1`;const user=rows[0];if(!user||user.otp_purpose!=="reset"||!user.otp_expires_at||new Date(user.otp_expires_at).getTime()<Date.now()||!equal(otpHash(code),user.otp_hash))return res.status(400).json({ok:false,error:"INVALID_OR_EXPIRED_CODE"});const passwordHash=hashPassword(password);await db`UPDATE rigo_users SET password_hash=${passwordHash},email_verified_at=COALESCE(email_verified_at,NOW()),otp_hash=NULL,otp_expires_at=NULL,otp_purpose=NULL,otp_sent_at=NULL,updated_at=NOW() WHERE id=${user.id}`;setSession(res,user,false);return res.status(200).json({ok:true,user:publicUser(user),role:user.role})}
  if(action==="login"){if(req.method!=="POST")return res.status(405).json({ok:false,error:"METHOD_NOT_ALLOWED"});const email=emailOf(body.email),password=String(body.password||"");const rows=await db`SELECT id,email,name,password_hash,role,email_verified_at FROM rigo_users WHERE email=${email} LIMIT 1`;const user=rows[0];if(!user||!verifyPassword(password,user.password_hash))return res.status(401).json({ok:false,error:"INVALID_CREDENTIALS"});if(!user.email_verified_at)return res.status(403).json({ok:false,error:"EMAIL_NOT_VERIFIED"});setSession(res,user,Boolean(body.staySignedIn));return res.status(200).json({ok:true,user:publicUser(user),role:user.role})}
  if(action==="logout"){if(req.method!=="POST")return res.status(405).json({ok:false,error:"METHOD_NOT_ALLOWED"});clearSession(res);return res.status(200).json({ok:true})}
  if(action==="session"){if(req.method!=="GET")return res.status(405).json({ok:false,error:"METHOD_NOT_ALLOWED"});const session=readToken(req);if(!session)return res.status(401).json({ok:false,user:null});const rows=await db`SELECT id,email,name,role,email_verified_at FROM rigo_users WHERE id=${session.id} LIMIT 1`;if(!rows.length||!rows[0].email_verified_at){clearSession(res);return res.status(401).json({ok:false,user:null})}return res.status(200).json({ok:true,user:publicUser(rows[0]),role:rows[0].role})}
  return res.status(400).json({ok:false,error:"INVALID_AUTH_ACTION"})
 }catch(error){return res.status(500).json({ok:false,error:error?.message||"RIGO_AUTH_FAILED"})}
}
